lorem_ipsum = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ac magna ullamcorper, mattis ante vitae, vehicula dolor. Suspendisse faucibus neque ac dolor faucibus viverra. Sed in erat sed lacus maximus scelerisque. Curabitur arcu velit, euismod ac sapien eget, porttitor facilisis dui. Nulla cursus a sem in vestibulum. Etiam finibus non ligula id finibus. Ut eget mi sem. Mauris tincidunt dolor odio, at finibus urna laoreet nec. Vestibulum vehicula tincidunt justo a convallis. Nunc vitae pellentesque libero. Mauris magna ex, sodales at lacinia a, aliquet sed est. Vestibulum id lacus pretium neque congue ultrices vel eget erat. Sed nisi nunc, maximus et scelerisque vestibulum, tristique sed tortor. In rutrum tortor sit amet eleifend iaculis. Phasellus tempor ligula sed vulputate viverra. Nam accumsan facilisis porta.

Vestibulum malesuada eleifend odio eget finibus. Nam ante dolor, fermentum sit amet risus eget, scelerisque porttitor velit. Duis blandit egestas sagittis. Morbi quam magna, iaculis id molestie sit amet, auctor vitae lectus. Praesent accumsan vulputate felis, et efficitur leo sagittis eu. Duis non dui dui. Suspendisse potenti. Duis bibendum a est id tincidunt. Mauris blandit est ut consequat condimentum. Aenean velit augue, sagittis in enim eu, interdum hendrerit purus. Aliquam lorem dolor, blandit ac lectus vitae, molestie pulvinar diam.

Maecenas posuere mi id ligula aliquet, vitae gravida lacus porta. Nam tempus ipsum lorem. Vivamus congue rhoncus velit. Praesent tempus suscipit porttitor. Ut eu dui sed erat finibus tincidunt vel vel nulla. Nulla non felis erat. Aliquam nisi eros, facilisis a tellus ac, iaculis laoreet velit. Integer lacinia finibus pretium. Aenean sed mauris quis diam aliquam auctor. Nulla nisl leo, aliquam nec consectetur id, consequat vitae nisi. Proin sed aliquam risus, quis accumsan arcu. Aliquam molestie odio erat, vel imperdiet magna finibus ut.

Vivamus aliquet lorem non semper finibus. Curabitur at mauris vel leo malesuada lacinia vitae et dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla bibendum sapien in sodales hendrerit. Ut convallis nisl sed pulvinar faucibus. In vel ligula leo. Nunc elit odio, scelerisque ac consequat in, mattis nec orci. Nam nec ornare lacus. Curabitur sed tristique enim, a finibus sem. Donec condimentum interdum lobortis. Nunc malesuada vitae ligula tincidunt porttitor. Praesent auctor magna nunc, ut mollis mi convallis a. Sed ipsum tellus, tempor in fringilla non, imperdiet a eros. Aenean efficitur ultrices leo, nec viverra massa vulputate ac. Cras gravida, quam id rhoncus faucibus, lacus odio efficitur massa, sit amet cursus justo tellus id dui.

Duis sed sollicitudin ipsum. Praesent vel viverra odio, quis efficitur velit. Mauris ut nunc nec orci vulputate vehicula vitae et dolor. Nam eget felis fringilla, sollicitudin eros eget, facilisis lorem. Sed lacinia semper nunc, ut finibus dolor pretium sit amet. Vestibulum iaculis porttitor mattis. Proin eget turpis sem. Vivamus at fringilla sem, vitae rhoncus turpis. Integer quis mollis velit, ac congue libero. Ut fermentum neque non mi ultricies, at consequat sapien bibendum."""

from side_by_side import print_side_by_side

li2 = lorem_ipsum
li2 = li2[:3] + '┌────────────────\n───────────────┬────────┐' + li2[3+len('┌───────────────────────────────┬────────┐'):]
print_side_by_side(lorem_ipsum, li2, print_line_numbers=False)